# This is meant to run in an openshift pod.
# The expectation is to create sandbox pods from this one.
FROM docker.io/usercont/sandcastle

COPY tests/requirements.txt ./tests/
RUN ansible-playbook -vv -c local -t with-sandcastle-deps -i localhost, install-rpm-packages.yaml \
    && dnf clean all

COPY . ./

CMD ["make", "check"]
