---
- name: Install dependencies for sandcastle.
  hosts: all
  tasks:
    - name: Install basic utilities which should be in a sandbox.
      ansible.builtin.dnf:
        name:
          - rsync # oc rsync worker:/sandcastle <-> sandcastle-pod
          - make
          - git-core
          - packit
          - rpmdevtools
          - automake
          - autoconf
          - libtool # https://github.com/TomasTomecek/libnbd/pull/1#issuecomment-554378236
          - tito
          - cmake
          - meson
          - ninja-build
          - wget
          - findutils
          - which
          - sed
          - gawk
          - python3-docutils # for those who generates man pages from README.md
          - python3-wheel # for python projects
          - json-c-devel # \
          - systemd-devel # https://github.com/Scribery/tlog/pull/274
          - libcurl-devel # /
          - python3-setuptools_scm # ansible-lint
          - rubygems # https://github.com/packit/packit-service/issues/771
          # needed for rust-based projects
          - rust
          - cargo
          - cargo2rpm
          # these are for cockpit
          - npm
          - selinux-policy
          - xmlto
          # these are for anaconda
          - glib2-devel
          - gettext-devel
          - python3-polib
          - gobject-introspection-devel
          - glade-devel
          - libxklavier-devel
          - libarchive-devel
          - rpm-devel
          - audit-libs-devel
          - nss_wrapper
          # so people can manipulate their upstream fmf definitions while proposing downstream
          - fmf
          # these are for node modules, requested for jowl
          - nodejs-packaging-bundler
          # for python projects using hatch-vcs
          - hatch
          - python3-hatch-vcs
          # for go-vendor-tools
          - trivy
          - askalono-cli
          - golang
        state: present
        install_weak_deps: False
      tags:
        - basic-image
    - name: Install python-build that is not packaged for EL9.
      ansible.builtin.pip:
        name: build
      tags:
        - basic-image

    - name: Install ‹rust2rpm› on CentOS Stream 9
      block:
        - name: Install ‹pip› of Python 3.11
          ansible.builtin.dnf:
            name: python3.11-pip
            state: present
            install_weak_deps: False
        - name: Install rust2rpm that is not packaged for EL9.
          ansible.builtin.pip:
            name: git+https://pagure.io/fedora-rust/rust2rpm.git
            # cargo2rpm is built for Python 3.11 (CentOS Stream 9)
            executable: pip3.11
      tags:
        - basic-image
      when: ansible_distribution == "CentOS"

    - name: Install ‹rust2rpm› on Fedora
      ansible.builtin.dnf:
        name: rust2rpm
        state: present
        install_weak_deps: False
      tags:
        - basic-image
      when: ansible_distribution == "Fedora"

    - name: Install go-vendor-tools that is not packaged for EL9.
      ansible.builtin.pip:
        name: go-vendor-tools
      tags:
        - basic-image
    - name: Install all RPM packages needed to hack on sandcastle.
      ansible.builtin.dnf:
        name:
          - git-core
          - python3-devel
          - python3-ipdb # for easy debugging
          - python3-pip
          - python3-setuptools
          - python3-setuptools_scm
          - python3-setuptools_scm_git_archive
          - python3-pytest # tests
        #          - python3-flexmock  # RHBZ#2120251
        state: present
      tags:
        - with-sandcastle-deps
    - name: Install Python client for kubernetes
      ansible.builtin.pip:
        name: kubernetes==12.0.1
      tags:
        - with-sandcastle-deps
    - name: Install OKD CLI (oc)
      ansible.builtin.unarchive:
        src: https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        remote_src: true
        dest: /usr/bin/
      tags:
        - with-sandcastle-deps
    - name: Install tests requirements
      ansible.builtin.pip:
        requirements: "{{ lookup('env','PWD') }}/tests/requirements.txt"
      tags:
        - with-sandcastle-deps
