---
- name: Install dependencies for sandcastle.
  hosts: all
  tasks:
    - name: Install basic utilities which should be in a sandbox.
      dnf:
        name:
          - rsync # oc rsync worker:/sandcastle <-> sandcastle-pod
          - make
          - git-core
          - packit
          - rpmdevtools
          - automake
          - autoconf
          - libtool # https://github.com/TomasTomecek/libnbd/pull/1#issuecomment-554378236
          - tito
          - cmake
          - meson
          - ninja-build
          - wget
          - curl
          - findutils
          - which
          - sed
          - gawk
          - python3-docutils # for those who generates man pages from README.md
          - python3-wheel # for python projects
          - json-c-devel # \
          - systemd-devel # https://github.com/Scribery/tlog/pull/274
          - libcurl-devel # /
          - python3-build # ansible-lint
          - python3-setuptools_scm # ansible-lint
          - python3-zanata-client # for those who use zanata for localization
          - python2 # https://github.com/packit-service/sandcastle/issues/49
          - python2-setuptools # /
          - rust # needed for rust-based projects
          - cargo #
          - rubygems # https://github.com/packit/packit-service/issues/771
          # these are for cockpit
          - npm
          - selinux-policy
          # these are for anaconda
          - glib2-devel
          - gettext-devel
          - python3-polib
          - gobject-introspection-devel
          - glade-devel
          - libxklavier-devel
          - libarchive-devel
          - rpm-devel
          - audit-libs-devel
          - nss_wrapper
          # so people can manipulate their upstream fmf definitions while proposing downstream
          - fmf
        state: present
      tags:
        - basic-image
    - name: Install all RPM packages needed to hack on sandcastle.
      dnf:
        name:
          - git-core
          - python3-devel
          - python3-ipdb # for easy debugging
          - python3-pip
          - python3-setuptools
          - python3-setuptools_scm
          - python3-setuptools_scm_git_archive
          - origin-clients # oc cp
          - python3-pytest # tests
          - python3-flexmock
        state: present
      tags:
        - with-sandcastle-deps
    - name: Install kubernetes client
      pip:
        executable: /usr/bin/pip3
        name: kubernetes==12.0.1
      tags:
        - with-sandcastle-deps
    - name: Install tests requirements
      pip:
        executable: /usr/bin/pip3
        requirements: "{{ lookup('env','PWD') }}/tests/requirements.txt"
      tags:
        - with-sandcastle-deps
