---
- name: Install Openshift cluster
  hosts: all
  tasks:
    - name: Install basic utilities which should be in environment
      dnf:
        name:
          - git
          - rpmdevtools
        state: present
      become: true
    - name: Install dependencies
      pip:
        name:
          - kubernetes<9
        executable: pip3
      become: true
    - name: Install test dependencies
      dnf:
        name:
          - python3-pytest
          - python3-flexmock
        state: present
      become: true
    - name: Setup Docker CE repo
      get_url:
        url: https://download.docker.com/linux/fedora/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644
      become: true
    - name: Install Docker CE
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      become: true
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive
      become: true
    - name: Make sure docker is running
      systemd:
        name: docker
        state: started
      become: true
    - name: Create docker deamon config
      file:
        path: /etc/docker/daemon.json
        state: touch
      become: true
    - name: Add OpenShift insecure registry into docker deamon config
      copy:
        content: |
          {"insecure-registries" : [ "172.30.0.0/16" ]}
        dest: /etc/docker/daemon.json
      become: true
    - name: Restart docker because config has changed
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker
      become: true
    - name: Install OpenShift server
      dnf:
        name:
          - origin
        state: present
      become: true
    - name: Start Openshift cluster
      command: oc cluster up --base-dir=/tmp --enable="-centos-imagestreams,-sample-templates,persistent-volumes,registry,router,-web-console"
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
        DOCKER_CONFIG: "/etc/docker/daemon.json"
      become: true
    # https://github.com/packit-service/sandcastle#developing-sandcastle
    - name: Add permissions for service account
      command: oc adm policy add-role-to-user edit system:serviceaccount:myproject:default
      become: true
